config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'plazas#index'
  resources :plazas, only: :index
  resources :posts, only: :new
  resources :users, only: :show do
    resources :lists, only: :index
  end
  resources :categories, only: :create
  resources :blogs, only: [:create, :show, :edit, :update, :destroy]
  resources :favorites, only: [:create, :show, :edit, :update, :destroy] do
    resources :memos, only: [:show, :new, :create, :edit, :update, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  belongs_to :category

  validates :blog_title, presence: true
  validates :blog_text,  presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :blogs
  has_many :favorites

  validates :category_name, presence: true
  validates :category_name, uniqueness: { scope: :user_id }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :memos

  validates :favorite_name,     presence: true
  validates :favorite_profile,  presence: true
  validates :favorite_image,  presence: true
  validates :favorite_name, uniqueness: { scope: :user_id }
end

app/models/memo.rb
class Memo < ApplicationRecord
  belongs_to :user
  belongs_to :favorite

  validates :memo_title, presence: true
  validates :memo_text,  presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :categories
  has_many :blogs
  has_many :favorites
  has_many :memos

  validates :user_name, presence: true, length: { maximum: 8 }
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:edit, :show,:update, :destroy]
  #before_action :set_user, only: :create

  def create
    @blog = Blog.new(blog_params)
    if @blog.save
      
    else
      @category = Category.new
      @favorite = Favorite.new
      render "posts/new"
    end
  end

  def show
  end

  def edit
  end

  def update
    @user =User.find(@blog.user_id)
    if @blog.update(blog_params) 
      
    else
      render :edit
    end
  end

  def destroy
    @user =User.find(@blog.user_id)
    if current_user.id == @blog.user_id
    @blog.destroy
    end
  end

  private
  def blog_params
    params.require(:blog).permit(:blog_title, :blog_text, :blog_image).merge(user_id: current_user.id, category_id: params[:category_id])
  end

  def set_blog
    @blog = Blog.find(params[:id])
  end

  def set_user
    @user = User.find(current_user.id)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_favorite, only: [:edit, :show, :update, :destroy]
  #before_action :set_user, only: :create

  def create
    @favorite = Favorite.new(favorite_params)
    if @favorite.save
      
    else
      @category = Category.new
      @blog = Blog.new
      render "posts/new"
    end
  end

  def show
    @memos = @favorite.memos.includes(:user)
  end

  def edit
  end

  def update
    @user =User.find(@favorite.user_id)
    if @favorite.update(favorite_params) 
      
    else
      render :edit
    end
  end

  def destroy
    @user =User.find(@favorite.user_id)
    if current_user.id == @favorite.user_id
    @favorite.destroy
    end
  end

  private

  def favorite_params
    params.require(:favorite).permit(:favorite_name, :favorite_profile, :favorite_image).merge(user_id: current_user.id, category_id: params[:category_id])
  end

  def set_favorite
    @favorite = Favorite.find(params[:id])
  end

  def set_user
    @user = User.find(current_user.id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @blog = @user.blogs.order("created_at DESC")
    @favorite = @user.favorites.order("created_at DESC")
  end
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  before_action :set_favorite, only: [:new, :edit, :update, :destroy]
  before_action :set_memo, only: [ :edit, :update, :destroy]
  
  def show
    @favorite = Favorite.find(params[:favorite_id])
    @memo = Memo.find(params[:id])
  end

  def new
    @memo = Memo.new
  end

  def create
    @memo = Memo.create(memo_params)
    unless @memo.save
      render :new
    end
  end

  def edit
    
  end

  def update
    @user =User.find(@memo.user_id)
    @memo.update(memo_params) 
    unless @memo.save
      render :edit
    end
  end

  def destroy
    @user =User.find(@memo.user_id)
    if current_user.id == @memo.user_id
      @memo.destroy
    end
  end

  private

  def set_favorite
    @favorite = Favorite.find(params[:favorite_id])
  end

  def set_memo
    @memo = Memo.find(params[:favorite_id])
  end

  def memo_params
    params.require(:memo).permit(:memo_title, :memo_text, :memo_image).merge(user_id: current_user.id, favorite_id: params[:favorite_id])
  end
end

app/controllers/plazas_controller.rb
class PlazasController < ApplicationController
  def index
    @blogs =Blog.order(updated_at: :desc).limit(3)
    @favorites =Favorite.order(updated_at: :desc).limit(3)
    @blogs_category = Category.joins(:blogs).group(:category_name).count
    @favorite_category = Category.joins(:favorites).group(:category_name).count
    @memo_category = Category.joins(favorites: :memos).group(:category_name).count
    @favorite_categories = @favorite_category.merge(@memo_category){|key, v1, v2| v1 + v2}
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @category = Category.new
    @blog = Blog.new
    @favorite = Favorite.new
  end

  private
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @blog = @user.blogs.order(updated_at: :desc).limit(1)
    @favorite = @user.favorites.order(updated_at: :desc).limit(1)
    #@blog = Blog.find(params[:id])
    #@favorite = Favorite.find(params[:id])
    @profile = @user.favorites.joins(:category).order(updated_at: :desc).find_by(categories:{category_name:"プロフィール"})
    #@profile = @user.favorites.find(1)
    @blog_categories = @user.categories.joins(:blogs).group(:category_name).count
    @favorite_categories = @user.categories.joins(:favorites).group(:category_name).count
    @memo_categories = @user.memos.joins(favorite: :category).group(:category_name).count
    #@categories = @blog_categories.merge(@favorite_categories, @memo_categories) 
    @categories = @blog_categories.merge(@favorite_categories, @memo_categories) {|key, v1, v2| v1 + v2}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/plazas_helper.rb
module PlazasHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/lists/index.html.erb
<%= render "shared/header" %>
<div class='main'>
  <div class=lists_body>
    <div class="contents row">
      <ul class='blog-lists'>
        <% @blog.each do |blog| %>
          <li class='list'>
            <%= link_to blog.blog_title, blog_path(blog.id), class: "blog" %>
          </li>
        <% end %>
      </ul>
      <ul class='favorite-lists'>
        <% @favorite.each do |favorite| %>
          <li class='list'>
            <div class="image_content">
              <img src="<%= favorite.favorite_image %>" alt="" class=list_image>
            </div>
            <%= link_to favorite.favorite_name, favorite_path(favorite.id), class: "favorite" %>
          </li>
        <% end %>
      </ul>
    </div>
    
  <div>
</div>
<%= render "shared/footer" %>

app/views/plazas/index.html.erb
<%= render "shared/header" %>
<div class='main'>
  <div class='title-contents'>
    <h2 class='service-title'>
      呪術廻戦、休載だった・・・
    </h2>
    <p class='service-explain'>
      鹿紫雲って性別どっちなの？？
    </p>
  </div>
  <div class="plaza_body">
    <div class="plaza_content">
      <div class="new_content">New Blog</div>
      <% @blogs.each do |blog| %>
        <div class="index_blog">
          <div class="image_content">
            <% if blog.blog_image == "" %>
              <%= image_tag"tasyumi_kiyoubinbou.png", class:"plaza_image" %>
            <% else%>  
              <img src="<%= blog.blog_image %>" alt="" class="plaza_image">
            <%end%>
          </div>
          <div class="plaza_blog">
            <p><%= link_to blog.blog_title, blog_path(blog.id), class: "index_title" %></p>
            <p>by.<%= link_to blog.user.user_name, user_path(blog.user.id), class: "index_user" %></p>
          </div>
        </div>
      <% end %>
    </div>
    <div class='plaza_content'>
      <div class="new_content">New Favorite</div>
      <% @favorites.each do |favorite| %>
        <div class="index_favorite">
          <div class="image_content">
            <img src="<%= favorite.favorite_image %>" alt="" class=plaza_image>
          </div>
          <div class="plaza_favorite">
          <p><%= link_to favorite.favorite_name, favorite_path(favorite.id), class: "index_name" %></p>
          <p>by.<%= link_to favorite.user.user_name, user_path(favorite.user.id), class: "index_user" %></p>
          </div>
        </div>
      <% end %>
    </div>
    <div class="plaza_content">
      <div class="chart_title">
      Blog's Category
      </div>
      <div class="plaza_chart">
        <%= pie_chart @blogs_category%>
      </div>
      <div class="chart_title">
      Favorite's Category
      </div>
      <div class="plaza_chart">
        <%= pie_chart @favorite_categories%>
      </div>
    </div>
  </div>
<div>
<%= render "shared/footer" %>

app/views/posts/new.html.erb
<%= render "shared/header" %>
<div class='main'>
  <div class="post_body">
    <div class="contents row">
      <div class="post_form">
        <h3>新しくカテゴリーを作る</h3>
        <%= form_with(model: @category, local: true) do |form| %> 
          <%= render 'shared/error_messages', model: form.object %>
          <input name="category[user_ids][]" type="hidden" value=<%= current_user.id %>>
          <%= form.text_field :category_name, placeholder: "カテゴリーを投稿してね" %>
          <%= form.submit "SEND" %>
        <% end %>
      </div>
      <div class="post_form">
        <h3>ブログを投稿する</h3>
        <%= form_with(model: @blog, local: true) do |form| %> 
          <%= render 'shared/error_messages', model: form.object %>
          <div class="select_category">
            <select name="category_id">
              <option value="">カテゴリーを選択してください</option>
              <% current_user.categories.each do |category| %>
                <option value=<%= category.id %>><%= category.category_name %></option>
              <% end %>
            </select>
          </div>
          <div class="img-upload">
            <p>GIF形式 (.gif）、JPEG形式（.jpg）、PNG形式（.png）※拡張子がない場合はつけてね！</p>
            <%= form.text_field :blog_image, placeholder: "Image Url", id:"item-image" %>
          </div>
          <div class="form_title">
            <%= form.text_field :blog_title, placeholder: "タイトル" %>
          </div>
          <div class="form_text">
            <%= form.text_area :blog_text, placeholder: "内容" %>
          </div>
          <%= form.submit "SEND" %>
        <% end %>
      </div>
      <div class="post_form">
        <h3>お気に入りを投稿する</h3>
        <%= form_with(model: @favorite, local: true) do |form| %> 
          <%= render 'shared/error_messages', model: form.object %>
          <div class="select_category">
            <select name="category_id">
              <option value="">カテゴリーを選択してください</option>
              <% current_user.categories.each do |category| %>
                <option value=<%= category.id %>><%= category.category_name %></option>
              <% end %>
            </select>
          </div>
          <div class="img-upload">
            <p>GIF形式 (.gif）、JPEG形式（.jpg）、PNG形式（.png）※拡張子がない場合はつけてね！</p>
            <%= form.text_field :favorite_image, placeholder: "Image Url", id:"item-image" %>
          </div>
          <div class="form_title">
            <%= form.text_field :favorite_name, placeholder: "名前" %>
          </div>
          <div class="form_text">
            <%= form.text_area :favorite_profile, placeholder: "詳細" %>
          </div>
          <%= form.submit "SEND" %>
        <% end %>
      </div>
    </div>
    <div class="contents row">
      <div class="container">
        <h3><%= current_user.user_name%>のカテゴリー一覧</h3>
      </div>
      <div class="categories_list">
        <% current_user.categories.each do |category| %>
          <p><%= category.category_name %></p>
        <% end %>
      </div>
    </div>
  </div>
</div>
<%= render "shared/footer" %>