config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'plazas#index'
  resources :plazas, only: :index
  resources :posts, only: :new
  resources :users, only: :show do
    resources :lists, only: :index
  end
  resources :categories, only: :create
  resources :blogs, only: [:create, :show, :edit, :update, :destroy]
  resources :favorites, only: [:create, :show, :edit, :update, :destroy] do
    resources :memos, only: [:show, :new, :create, :edit, :update, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  belongs_to :category

  validates :blog_title, presence: true
  validates :blog_text,  presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :blogs
  has_many :favorites

  validates :category_name, presence: true
  validates :category_name, uniqueness: { scope: :user_id }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :memos

  validates :favorite_name,     presence: true
  validates :favorite_profile,  presence: true
  validates :favorite_image,  presence: true
  validates :favorite_name, uniqueness: { scope: :user_id }
end

app/models/memo.rb
class Memo < ApplicationRecord
  belongs_to :user
  belongs_to :favorite

  validates :memo_title, presence: true
  validates :memo_text,  presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :categories
  has_many :blogs
  has_many :favorites
  has_many :memos

  validates :user_name, presence: true, length: { maximum: 8 }
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:edit, :show,:update, :destroy]
  #before_action :set_user, only: :create

  def create
    @blog = Blog.new(blog_params)
    if @blog.save
      
    else
      @category = Category.new
      @favorite = Favorite.new
      render "posts/new"
    end
  end

  def show
  end

  def edit
  end

  def update
    @user =User.find(@blog.user_id)
    if @blog.update(blog_params) 
      
    else
      render :edit
    end
  end

  def destroy
    @user =User.find(@blog.user_id)
    if current_user.id == @blog.user_id
    @blog.destroy
    end
  end

  private
  def blog_params
    params.require(:blog).permit(:blog_title, :blog_text, :blog_image).merge(user_id: current_user.id, category_id: params[:category_id])
  end

  def set_blog
    @blog = Blog.find(params[:id])
  end

  def set_user
    @user = User.find(current_user.id)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def create
    @category = Category.new(category_params)
    if @category.save
      
    else
      @blog = Blog.new
      @favorite = Favorite.new
      render "posts/new"
    end
  end

  private
  def category_params
    params.require(:category).permit(:category_name ).merge(user_id: current_user.id )
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_favorite, only: [:edit, :show, :update, :destroy]
  #before_action :set_user, only: :create

  def create
    @favorite = Favorite.new(favorite_params)
    if @favorite.save
      
    else
      @category = Category.new
      @blog = Blog.new
      render "posts/new"
    end
  end

  def show
    @memos = @favorite.memos.includes(:user)
  end

  def edit
  end

  def update
    @user =User.find(@favorite.user_id)
    if @favorite.update(favorite_params) 
      
    else
      render :edit
    end
  end

  def destroy
    @user =User.find(@favorite.user_id)
    if current_user.id == @favorite.user_id
    @favorite.destroy
    end
  end

  private

  def favorite_params
    params.require(:favorite).permit(:favorite_name, :favorite_profile, :favorite_image).merge(user_id: current_user.id, category_id: params[:category_id])
  end

  def set_favorite
    @favorite = Favorite.find(params[:id])
  end

  def set_user
    @user = User.find(current_user.id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @blog = @user.blogs.order("created_at DESC")
    @favorite = @user.favorites.order("created_at DESC")
  end
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  before_action :set_favorite, only: [:new, :edit, :update, :destroy]
  before_action :set_memo, only: [ :edit, :update, :destroy]
  
  def show
    @favorite = Favorite.find(params[:favorite_id])
    @memo = Memo.find(params[:id])
  end

  def new
    @memo = Memo.new
  end

  def create
    @memo = Memo.create(memo_params)
    unless @memo.save
      render :new
    end
  end

  def edit
    
  end

  def update
    @user =User.find(@memo.user_id)
    @memo.update(memo_params) 
    unless @memo.save
      render :edit
    end
  end

  def destroy
    @user =User.find(@memo.user_id)
    if current_user.id == @memo.user_id
      @memo.destroy
    end
  end

  private

  def set_favorite
    @favorite = Favorite.find(params[:favorite_id])
  end

  def set_memo
    @memo = Memo.find(params[:favorite_id])
  end

  def memo_params
    params.require(:memo).permit(:memo_title, :memo_text, :memo_image).merge(user_id: current_user.id, favorite_id: params[:favorite_id])
  end
end

app/controllers/plazas_controller.rb
class PlazasController < ApplicationController
  def index
    @blogs =Blog.order(updated_at: :desc).limit(3)
    @favorites =Favorite.order(updated_at: :desc).limit(3)
    @blogs_category = Category.joins(:blogs).group(:category_name).count
    @favorite_category = Category.joins(:favorites).group(:category_name).count
    @memo_category = Category.joins(favorites: :memos).group(:category_name).count
    @favorite_categories = @favorite_category.merge(@memo_category){|key, v1, v2| v1 + v2}
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @category = Category.new
    @blog = Blog.new
    @favorite = Favorite.new
  end

  private
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @blog = @user.blogs.order(updated_at: :desc).limit(1)
    @favorite = @user.favorites.order(updated_at: :desc).limit(1)
    #@blog = Blog.find(params[:id])
    #@favorite = Favorite.find(params[:id])
    @profile = @user.favorites.joins(:category).order(updated_at: :desc).find_by(categories:{category_name:"プロフィール"})
    #@profile = @user.favorites.find(1)
    @blog_categories = @user.categories.joins(:blogs).group(:category_name).count
    @favorite_categories = @user.categories.joins(:favorites).group(:category_name).count
    @memo_categories = @user.memos.joins(favorite: :category).group(:category_name).count
    #@categories = @blog_categories.merge(@favorite_categories, @memo_categories) 
    @categories = @blog_categories.merge(@favorite_categories, @memo_categories) {|key, v1, v2| v1 + v2}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/plazas_helper.rb
module PlazasHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/create.html.erb
<%= render "shared/header" %>
<div class="contents row">
  <div class="success">
    <h3>ブログの投稿が完了しました。</h3>
  </div>
</div>
<%= render "shared/footer" %>

app/views/blogs/destroy.html.erb
<%= render "shared/header" %>
<div class="contents row">
  <div class="success">
    <h3>ブログの削除が完了しました。</h3>
  </div>
  <div class="post_list">
    <%= link_to "投稿一覧へ戻る", user_lists_path(@user.id), class: "user_lists" %>
  </div>
</div>
<%= render "shared/footer" %>

app/views/blogs/edit.html.erb
<%= render "shared/header" %>
<div class='main'>
  <div class="post_body">
    <div class="contents row">
      <div class="container">
        <h3>ブログを編集する</h3>
        <%= form_with(model: @blog, local: true) do |form| %> 
          <div class="blog_category">
            <select name="category_id">
              <!--<option value="">カテゴリーを選択してください</option>-->
              <% current_user.categories.each do |category| %>
                <option value=<%= category.id %>><%= category.category_name %></option>
              <% end %>
            </select>
          </div>
          <div class="blog_title">
            <%= form.text_field :blog_title, placeholder: "タイトル" %>
          </div>
          <div class="blog_text">
            <%= form.text_area :blog_text, placeholder: "内容" %>
          </div>
          <%= form.submit "SEND" %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<%= render "shared/footer" %>

app/views/blogs/index.html.erb
<%= render "shared/header" %>
<div class="contents row">
  
</div>
<%= render "shared/footer" %>

app/views/blogs/show.html.erb
<%= render "shared/header" %>
<div class='main'>
  <div class="blog_body">
    <div class="content_blog">
      <div class="image_content">
        <% if @blog.blog_image == "" %>
          <%= image_tag"tasyumi_kiyoubinbou.png", class:"index_image" %>
        <% else%>  
          <img src="<%= @blog.blog_image %>" alt="" class="index_image">
        <%end%>
      </div>
      <div class="blog_header">
        <p><%= @blog.blog_title %></p>
        <% if user_signed_in? && current_user.id == @blog.user_id %>
          <div class="more">
            <ul class="more_list">
              <li>
                <%= link_to '編集', edit_blog_path(@blog.id), method: :get %>
              </li>
              <li>
                <%= link_to '削除', blog_path(@blog.id), method: :delete %>
              </li>
            </ul>
          </div>
        <% end %>
      </div>
      <p><%= safe_join(@blog.blog_text.split("\n"),tag(:br)) %></p>
      <div class="day"><%= l @blog.created_at %></div>
    </div>
  </div>
</div>
<%= render "shared/footer" %>

app/views/blogs/update.html.erb
<%= render "shared/header" %>
<div class="contents row">
  <div class="success">
    <h3>ブログの編集が完了しました。</h3>
  </div>
  <div class="post_list">
    <%= link_to "投稿一覧へ戻る", user_lists_path(@user.id), class: "user_lists" %>
  </div>
</div>
<%= render "shared/footer" %>

app/views/categories/create.html.erb
<%= render "shared/header" %>
<div class="contents row">
  <div class="success">
    <h3>カテゴリーの作成が完了しました。</h3>
  </div>
</div>
<%= render "shared/footer" %>

app/views/favorites/create.html.erb
<%= render "shared/header" %>
<div class="contents row">
  <div class="success">
    <h3>お気に入りの投稿が完了しました。</h3>
  </div>
</div>
<%= render "shared/footer" %>

app/views/favorites/destroy.html.erb
<%= render "shared/header" %>
<div class="contents row">
  <div class="success">
    <h3>お気に入りの削除が完了しました。</h3>
  </div>
  <div class="post_list">
    <%= link_to "投稿一覧へ戻る", user_lists_path(@user.id), class: "user_lists" %>
  </div>
</div>
<%= render "shared/footer" %>

app/views/favorites/edit.html.erb
<%= render "shared/header" %>
<div class='main'>
  <div class="post_body">
    <div class="contents row">
      <div class="container">
        <h3>お気に入りを編集する</h3>
        <%= form_with(model: @favorite, local: true) do |form| %> 
          <div class="edit_category">
            <select name="category_id">
              <!--<option value="">カテゴリーを選択してください</option>-->
              <% current_user.categories.each do |category| %>
                <option value=<%= category.id %>><%= category.category_name %></option>
              <% end %>
            </select>
          </div>
          <div class="img-upload">
            <p>GIF形式 (.gif）、JPEG形式（.jpg）、PNG形式（.png）※拡張子がない場合はつけてね！</p>
            <%= form.text_field :favorite_image, placeholder: "Image Url", id:"item-image" %>
          </div>
          <div class="form_title">
            <%= form.text_field :favorite_name, placeholder: "名前" %>
          </div>
          <div class="form_text">
            <%= form.text_area :favorite_profile, placeholder: "詳細" %>
          </div>
          <%= form.submit "SEND" %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<%= render "shared/footer" %>

app/views/favorites/show.html.erb
<%= render "shared/header" %>
<div class='main'>
  <div class="favorite_body">
    <div class="content_favorite">
      <div class="image_content">
        <img src="<%= @favorite.favorite_image %>" alt="" class=index_image>
      </div>
      <div class="blog_header">
        <p><%= @favorite.favorite_name %></p>
        <% if user_signed_in? && current_user.id == @favorite.user_id %>
          <div class="more">
            <ul class="more_list">
              <li>
                <%= link_to '編集', edit_favorite_path(@favorite.id), method: :get %>
              </li>
              <li>
                <%= link_to 'メモ', new_favorite_memo_path(@favorite.id), method: :get %>
              </li>
              <li>
                <%= link_to '削除', favorite_path(@favorite.id), method: :delete %>
              </li>
            </ul>
          </div>
        <% end %>
      </div>
      <p><%= safe_join(@favorite.favorite_profile.split("\n"),tag(:br)) %></p>
      <div class="day"><%= l @favorite.created_at %></div>
    </div>
    <div class="memos">
      <h4>＜メモ一覧＞</h4>
      <% @memos.each do |memo| %>
        <div class="content_memo">
          <div class="memo_header">
            <p><%= link_to memo.memo_title, favorite_memo_path(@favorite.id, memo.id), class: "memo_link" %></p>
          </div>
          <div class="day"><%= l memo.created_at %></div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<%= render "shared/footer" %>

app/views/favorites/update.html.erb
<%= render "shared/header" %>
<div class="contents row">
  <div class="success">
    <h3>お気に入りの編集が完了しました。</h3>
  </div>
  <div class="post_list">
    <%= link_to "投稿一覧へ戻る", user_lists_path(@user.id), class: "user_lists" %>
  </div>
</div>
<%= render "shared/footer" %>

app/views/memos/create.html.erb
<%= render "shared/header" %>
<div class="contents row">
  <div class="success">
    <h3>メモの投稿が完了しました。</h3>
  </div>
</div>
<%= render "shared/footer" %>

app/views/memos/destroy.html.erb
<%= render "shared/header" %>
<div class="contents row">
  <div class="success">
    <h3>メモの削除が完了しました。</h3>
  </div>
  <div class="post_list">
    <%= link_to "お気に入り詳細へ戻る", favorite_path(@favorite.id), class: "user_lists" %>
  </div>
</div>
<%= render "shared/footer" %>

app/views/memos/edit.html.erb
<%= render "shared/header" %>
<div class='main'>
  <div class="post_body">
    <div class="contents row">
      <div class="container">
        <h3>メモを編集する</h3>
        <%= form_with(model:[@favorite, @memo], local: true) do |form| %> 
          <div class="img-upload">
            <p>GIF形式 (.gif）、JPEG形式（.jpg）、PNG形式（.png）※拡張子がない場合はつけてね！</p>
            <%= form.text_field :memo_image, placeholder: "Image Url", id:"item-image" %>
          </div>
          <div class="form_title">
            <%= form.text_field :memo_title, placeholder: "タイトル" %>
          </div>
          <div class="form_text">
            <%= form.text_area :memo_text, placeholder: "内容" %>
          </div>
          <%= form.submit "SEND" %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<%= render "shared/footer" %>

app/views/memos/new.html.erb
<%= render "shared/header" %>
<div class='main'>
  <div class="post_body">
    <div class="contents row">
      <div class="content_blog">
        <div class="image_content">
          <img src="<%= @favorite.favorite_image %>" alt="" class=index_image>
        </div>
        <div class="blog_header">
          <p><%= @favorite.favorite_name %></p>
        </div>
        <p><%= safe_join(@favorite.favorite_profile.split("\n"),tag(:br)) %></p>
      </div>
      <div class="post_form">
        <h3>メモを投稿する</h3>
        <%= form_with(model: [@favorite, @memo], local: true) do |form| %> 
          <%= render 'shared/error_messages', model: form.object %>
          <div class="img-upload">
            <p>GIF形式 (.gif）、JPEG形式（.jpg）、PNG形式（.png）※拡張子がない場合はつけてね！</p>
            <%= form.text_field :memo_image, placeholder: "Image Url", id:"item-image" %>
          </div>
          <div class="form_title">
            <%= form.text_field :memo_title, placeholder: "タイトル" %>
          </div>
          <div class="form_text">
            <%= form.text_area :memo_text, placeholder: "内容" %>
          </div>
          <%= form.submit "SEND" %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<%= render "shared/footer" %>

app/views/memos/show.html.erb
<%= render "shared/header" %>
<div class='main'>
  <div class="blog_body">
    <div class="content_memo">
      <div class="image_content">
        <% if @memo.memo_image == "" %>
          <%= image_tag"tasyumi_kiyoubinbou.png", class:"index_image" %>
        <% else%>  
          <img src="<%= @memo.memo_image %>" alt="" class="index_image">
        <%end%>
      </div>
      <div class="blog_header">
        <p><%= @memo.memo_title %></p>
        <% if user_signed_in? && current_user.id == @memo.user_id %>
          <div class="more">
            <ul class="more_list">
              <li>
                <%= link_to '編集', edit_favorite_memo_path(@memo.id), method: :get %>
              </li>
              <li>
                <%= link_to '削除', favorite_memo_path(@memo.id), method: :delete %>
              </li>
            </ul>
          </div>
        <% end %>
      </div>
      <p><%= safe_join(@memo.memo_text.split("\n"),tag(:br)) %></p>
      <div class="day"><%= l @memo.created_at %></div>
    </div>
  </div>
</div>
<%= render "shared/footer" %>

app/views/memos/update.html.erb
<%= render "shared/header" %>
<div class="contents row">
  <div class="success">
    <h3>メモの編集が完了しました。</h3>
  </div>
  <div class="post_list">
    <%= link_to "お気に入り詳細へ戻る", favorite_path(@favorite.id), class: "user_lists" %>
  </div>
</div>
<%= render "shared/footer" %>

app/views/users/show.html.erb
<%= render "shared/header" %>
<div class='main'>
  <div class="contents row">
    <div class="user_profile">
      <div class="user_left">
        <% if @profile == nil %>
          <%= image_tag"tasyumi_kiyoubinbou.png", class:"user_image" %>
        <% else%>  
          <img src="<%= @profile.favorite_image %>" alt="" class="user_image">
        <%end%>
      </div>
      <div class="user_light">
        <div class="user_chart">
          <%= pie_chart @categories%>
        </div>
        <div class="myname">
          <%= @user.user_name %>
        </div>
        <div class="mytext">
          <% unless @profile == nil %>
            <%= @profile.favorite_profile %>
          <%end%>
        </div>
      </div>
    </div>
    <div class="users_new">
      <div class="user_newblog">New Blog</div>
      <div class="user_newfavorite">New Favorite</div>
      <div class="user_status">Status</div>
    </div>
    <div class="user_content">
      <div class="user_blogs">
        <% @blog.each do |blog| %>
          <div class="u_b_image">
            <% if blog.blog_image == "" %>
              <%= image_tag"tasyumi_kiyoubinbou.png", class:"u_b_i_content" %>
            <%else%>
              <img src="<%= blog.blog_image %>" alt="" class="u_b_i_content">
            <%end%>
          </div>
          <div class="u_b_content">
            <div class="u_b_title"><%= link_to blog.blog_title, blog_path(blog.id), class:"u_b_link" %></div>
            <div class="u_b_text"><%= safe_join(blog.blog_text.split("\n"),tag(:br)) %></div>
          </div>
        <% end %>
      </div>
      <div class="user_favorites">
        <% @favorite.each do |favorite| %>
          <div class="u_f_image">
            <img src="<%= favorite.favorite_image %>" alt="" class="u_f_i_content">
          </div>
          <div class="blog_header">
            <p><%= link_to favorite.favorite_name, favorite_path(favorite.id) %></p>
          </div>
          <p><%= safe_join(favorite.favorite_profile.split("\n"),tag(:br)) %></p>
        <% end %>
      </div>
      <div class="user_posts">
        <%= link_to "投稿一覧", user_lists_path(@user.id), class: "user_lists" %>
      </div>
    </div>
  </div>
</div>
<%= render "shared/footer" %>