config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'plazas#index'
  resources :plazas, only: :index
  resources :posts, only: :new
  resources :users, only: :show do
    resources :lists, only: :index
  end
  resources :categories, only: :create
  resources :blogs, only: [:create, :show, :edit, :update, :destroy]
  resources :favorites, only: [:create, :show, :edit, :update, :destroy] do
    resources :memos, only: [:show, :new, :create, :edit, :update, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  belongs_to :category

  validates :blog_title, presence: true
  validates :blog_text,  presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :blogs
  has_many :favorites

  validates :category_name, presence: true
  validates :category_name, uniqueness: { scope: :user_id }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :memos

  validates :favorite_name,     presence: true
  validates :favorite_profile,  presence: true
  validates :favorite_image,  presence: true
  validates :favorite_name, uniqueness: { scope: :user_id }
end

app/models/memo.rb
class Memo < ApplicationRecord
  belongs_to :user
  belongs_to :favorite

  validates :memo_title, presence: true
  validates :memo_text,  presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :categories
  has_many :blogs
  has_many :favorites
  has_many :memos

  validates :user_name, presence: true, length: { maximum: 8 }
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:edit, :show,:update, :destroy]
  #before_action :set_user, only: :create

  def create
    @blog = Blog.new(blog_params)
    if @blog.save
      
    else
      @category = Category.new
      @favorite = Favorite.new
      render "posts/new"
    end
  end

  def show
  end

  def edit
  end

  def update
    @user =User.find(@blog.user_id)
    if @blog.update(blog_params) 
      
    else
      render :edit
    end
  end

  def destroy
    @user =User.find(@blog.user_id)
    if current_user.id == @blog.user_id
    @blog.destroy
    end
  end

  private
  def blog_params
    params.require(:blog).permit(:blog_title, :blog_text, :blog_image).merge(user_id: current_user.id, category_id: params[:category_id])
  end

  def set_blog
    @blog = Blog.find(params[:id])
  end

  def set_user
    @user = User.find(current_user.id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @blog = @user.blogs.order("created_at DESC")
    @favorite = @user.favorites.order("created_at DESC")
  end
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  before_action :set_favorite, only: [:new, :edit, :update, :destroy]
  before_action :set_memo, only: [ :edit, :update, :destroy]
  
  def show
    @favorite = Favorite.find(params[:favorite_id])
    @memo = Memo.find(params[:id])
  end

  def new
    @memo = Memo.new
  end

  def create
    @memo = Memo.create(memo_params)
    unless @memo.save
      render :new
    end
  end

  def edit
    
  end

  def update
    @user =User.find(@memo.user_id)
    @memo.update(memo_params) 
    unless @memo.save
      render :edit
    end
  end

  def destroy
    @user =User.find(@memo.user_id)
    if current_user.id == @memo.user_id
      @memo.destroy
    end
  end

  private

  def set_favorite
    @favorite = Favorite.find(params[:favorite_id])
  end

  def set_memo
    @memo = Memo.find(params[:favorite_id])
  end

  def memo_params
    params.require(:memo).permit(:memo_title, :memo_text, :memo_image).merge(user_id: current_user.id, favorite_id: params[:favorite_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @category = Category.new
    @blog = Blog.new
    @favorite = Favorite.new
  end

  private
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @blog = @user.blogs.order(updated_at: :desc).limit(1)
    @favorite = @user.favorites.order(updated_at: :desc).limit(1)
    #@blog = Blog.find(params[:id])
    #@favorite = Favorite.find(params[:id])
    @profile = @user.favorites.joins(:category).order(updated_at: :desc).find_by(categories:{category_name:"プロフィール"})
    #@profile = @user.favorites.find(1)
    @blog_categories = @user.categories.joins(:blogs).group(:category_name).count
    @favorite_categories = @user.categories.joins(:favorites).group(:category_name).count
    @memo_categories = @user.memos.joins(favorite: :category).group(:category_name).count
    #@categories = @blog_categories.merge(@favorite_categories, @memo_categories) 
    @categories = @blog_categories.merge(@favorite_categories, @memo_categories) {|key, v1, v2| v1 + v2}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/plazas_helper.rb
module PlazasHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Interest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div class='footer'>
  <div class='footer-contents'>
    <div class='interest-details'>
      <h2 class='footer-content-head'>Interestについて</h2>
      <ul>
        <li><%= link_to '会社概要（運営会社)', "#", class: "footer-link" %></li>
        <li><%= link_to 'プライバシーポリシー', "#", class: "footer-link" %></li>
        <li><%= link_to 'Interest利用規約', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='interest-details'>
      <h2 class='footer-content-head'>ブログ、お気に入りを見る</h2>
      <ul>
        <li><%= link_to 'カテゴリー一覧', "#", class: "footer-link" %></li>
      </ul>
    </div>
    </div>
      <div class='store-btn'>
      <%= link_to image_tag("app-store.svg", class:"apple-btn"), "#" %>
      <%= link_to image_tag("google-play.png", class:"google-btn"), "#" %>
    </div>
  <p>© Interest</p>
</div>

app/views/shared/_header.html.erb
<header class='top-page-header'>
  <div class='header_logo'>
    <%= link_to 'Interest', "/", class:"interest-logo" %>
  </div>
  <div class='nav'>
    <ul class='lists-right'>
      <% if user_signed_in? %>
        <li><%= link_to current_user.user_name, user_path(current_user.id), class: "user-nickname" %></li> 
        <li><%= link_to '投稿する', new_post_path(current_user.id), class:"new_post" %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
      <% else %>
        <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
    </ul>
  </div>
</header>